package com.chen.plane.domain.pojo;

public class City {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.CITY_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.CITY_NAME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String cityName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column city.CITY_CODE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String cityCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.CITY_ID
     *
     * @return the value of city.CITY_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getCityId() {
        return cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.CITY_ID
     *
     * @param cityId the value for city.CITY_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.CITY_NAME
     *
     * @return the value of city.CITY_NAME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getCityName() {
        return cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.CITY_NAME
     *
     * @param cityName the value for city.CITY_NAME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column city.CITY_CODE
     *
     * @return the value of city.CITY_CODE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getCityCode() {
        return cityCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column city.CITY_CODE
     *
     * @param cityCode the value for city.CITY_CODE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setCityCode(String cityCode) {
        this.cityCode = cityCode;
    }

    @Override public String toString() {
        return "City{" +
                "cityId=" + cityId +
                ", cityName='" + cityName + '\'' +
                ", cityCode='" + cityCode + '\'' +
                '}';
    }
}