package com.chen.plane.domain.pojo;

import java.util.Date;

public class OutTicket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_ticket.OUT_TICKET_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer outTicketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_ticket.TICKET_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer ticketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_ticket.OUT_TICKET_IP
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String outTicketIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_ticket.OUT_TICKET_ADDRESS
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String outTicketAddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_ticket.OUT_TICKET_MACHINE_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer outTicketMachineId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_ticket.OUT_TICKET_STATUE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer outTicketStatue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_ticket.OUT_TICKET_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Date outTicketTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column out_ticket.OUT_TICKET_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String outTicketNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_ticket.OUT_TICKET_ID
     *
     * @return the value of out_ticket.OUT_TICKET_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getOutTicketId() {
        return outTicketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_ticket.OUT_TICKET_ID
     *
     * @param outTicketId the value for out_ticket.OUT_TICKET_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setOutTicketId(Integer outTicketId) {
        this.outTicketId = outTicketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_ticket.TICKET_ID
     *
     * @return the value of out_ticket.TICKET_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_ticket.TICKET_ID
     *
     * @param ticketId the value for out_ticket.TICKET_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_ticket.OUT_TICKET_IP
     *
     * @return the value of out_ticket.OUT_TICKET_IP
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getOutTicketIp() {
        return outTicketIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_ticket.OUT_TICKET_IP
     *
     * @param outTicketIp the value for out_ticket.OUT_TICKET_IP
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setOutTicketIp(String outTicketIp) {
        this.outTicketIp = outTicketIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_ticket.OUT_TICKET_ADDRESS
     *
     * @return the value of out_ticket.OUT_TICKET_ADDRESS
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getOutTicketAddress() {
        return outTicketAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_ticket.OUT_TICKET_ADDRESS
     *
     * @param outTicketAddress the value for out_ticket.OUT_TICKET_ADDRESS
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setOutTicketAddress(String outTicketAddress) {
        this.outTicketAddress = outTicketAddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_ticket.OUT_TICKET_MACHINE_ID
     *
     * @return the value of out_ticket.OUT_TICKET_MACHINE_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getOutTicketMachineId() {
        return outTicketMachineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_ticket.OUT_TICKET_MACHINE_ID
     *
     * @param outTicketMachineId the value for out_ticket.OUT_TICKET_MACHINE_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setOutTicketMachineId(Integer outTicketMachineId) {
        this.outTicketMachineId = outTicketMachineId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_ticket.OUT_TICKET_STATUE
     *
     * @return the value of out_ticket.OUT_TICKET_STATUE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getOutTicketStatue() {
        return outTicketStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_ticket.OUT_TICKET_STATUE
     *
     * @param outTicketStatue the value for out_ticket.OUT_TICKET_STATUE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setOutTicketStatue(Integer outTicketStatue) {
        this.outTicketStatue = outTicketStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_ticket.OUT_TICKET_TIME
     *
     * @return the value of out_ticket.OUT_TICKET_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Date getOutTicketTime() {
        return outTicketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_ticket.OUT_TICKET_TIME
     *
     * @param outTicketTime the value for out_ticket.OUT_TICKET_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setOutTicketTime(Date outTicketTime) {
        this.outTicketTime = outTicketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column out_ticket.OUT_TICKET_NUMBER
     *
     * @return the value of out_ticket.OUT_TICKET_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getOutTicketNumber() {
        return outTicketNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column out_ticket.OUT_TICKET_NUMBER
     *
     * @param outTicketNumber the value for out_ticket.OUT_TICKET_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setOutTicketNumber(String outTicketNumber) {
        this.outTicketNumber = outTicketNumber;
    }

    @Override public String toString() {
        return "OutTicket{" +
                "outTicketId=" + outTicketId +
                ", ticketId=" + ticketId +
                ", outTicketIp='" + outTicketIp + '\'' +
                ", outTicketAddress='" + outTicketAddress + '\'' +
                ", outTicketMachineId=" + outTicketMachineId +
                ", outTicketStatue=" + outTicketStatue +
                ", outTicketTime=" + outTicketTime +
                ", outTicketNumber='" + outTicketNumber + '\'' +
                '}';
    }
}