package com.chen.plane.domain.pojo;

import java.util.Date;

public class PAY {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.PAY_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer payId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.TICKET_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer ticketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.PAY_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Date payTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.PAY_IP
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String payIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.PAY_TYPE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer payType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.PAY_MONEY
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Double payMoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.PAY_STATUE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer payStatue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.PAY_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String payNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pay.BANK_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String bankNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.PAY_ID
     *
     * @return the value of pay.PAY_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.PAY_ID
     *
     * @param payId the value for pay.PAY_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPayId(Integer payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.TICKET_ID
     *
     * @return the value of pay.TICKET_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.TICKET_ID
     *
     * @param ticketId the value for pay.TICKET_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.PAY_TIME
     *
     * @return the value of pay.PAY_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Date getPayTime() {
        return payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.PAY_TIME
     *
     * @param payTime the value for pay.PAY_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPayTime(Date payTime) {
        this.payTime = payTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.PAY_IP
     *
     * @return the value of pay.PAY_IP
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getPayIp() {
        return payIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.PAY_IP
     *
     * @param payIp the value for pay.PAY_IP
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPayIp(String payIp) {
        this.payIp = payIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.PAY_TYPE
     *
     * @return the value of pay.PAY_TYPE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.PAY_TYPE
     *
     * @param payType the value for pay.PAY_TYPE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.PAY_MONEY
     *
     * @return the value of pay.PAY_MONEY
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Double getPayMoney() {
        return payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.PAY_MONEY
     *
     * @param payMoney the value for pay.PAY_MONEY
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPayMoney(Double payMoney) {
        this.payMoney = payMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.PAY_STATUE
     *
     * @return the value of pay.PAY_STATUE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getPayStatue() {
        return payStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.PAY_STATUE
     *
     * @param payStatue the value for pay.PAY_STATUE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPayStatue(Integer payStatue) {
        this.payStatue = payStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.PAY_NUMBER
     *
     * @return the value of pay.PAY_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getPayNumber() {
        return payNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.PAY_NUMBER
     *
     * @param payNumber the value for pay.PAY_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPayNumber(String payNumber) {
        this.payNumber = payNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pay.BANK_NUMBER
     *
     * @return the value of pay.BANK_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getBankNumber() {
        return bankNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pay.BANK_NUMBER
     *
     * @param bankNumber the value for pay.BANK_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setBankNumber(String bankNumber) {
        this.bankNumber = bankNumber;
    }

    @Override public String toString() {
        return "PAY{" +
                "payId=" + payId +
                ", ticketId=" + ticketId +
                ", payTime=" + payTime +
                ", payIp='" + payIp + '\'' +
                ", payType=" + payType +
                ", payMoney=" + payMoney +
                ", payStatue=" + payStatue +
                ", payNumber='" + payNumber + '\'' +
                ", bankNumber='" + bankNumber + '\'' +
                '}';
    }
}