package com.chen.plane.domain.pojo;

public class PlanePool {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_pool.TICKET_POOL_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer ticketPoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_pool.PLANE_INFO_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer planeInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_pool.TICKET_POOL_SUM
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer ticketPoolSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_pool.TICKET_POOL_SALE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer ticketPoolSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_pool.TAKE_OFF_PLACE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer takeOffPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_pool.TAKE_ON_PLACE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer takeOnPlace;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_pool.TICKET_POOL_ID
     *
     * @return the value of plane_pool.TICKET_POOL_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getTicketPoolId() {
        return ticketPoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_pool.TICKET_POOL_ID
     *
     * @param ticketPoolId the value for plane_pool.TICKET_POOL_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketPoolId(Integer ticketPoolId) {
        this.ticketPoolId = ticketPoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_pool.PLANE_INFO_ID
     *
     * @return the value of plane_pool.PLANE_INFO_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getPlaneInfoId() {
        return planeInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_pool.PLANE_INFO_ID
     *
     * @param planeInfoId the value for plane_pool.PLANE_INFO_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPlaneInfoId(Integer planeInfoId) {
        this.planeInfoId = planeInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_pool.TICKET_POOL_SUM
     *
     * @return the value of plane_pool.TICKET_POOL_SUM
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getTicketPoolSum() {
        return ticketPoolSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_pool.TICKET_POOL_SUM
     *
     * @param ticketPoolSum the value for plane_pool.TICKET_POOL_SUM
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketPoolSum(Integer ticketPoolSum) {
        this.ticketPoolSum = ticketPoolSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_pool.TICKET_POOL_SALE
     *
     * @return the value of plane_pool.TICKET_POOL_SALE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getTicketPoolSale() {
        return ticketPoolSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_pool.TICKET_POOL_SALE
     *
     * @param ticketPoolSale the value for plane_pool.TICKET_POOL_SALE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketPoolSale(Integer ticketPoolSale) {
        this.ticketPoolSale = ticketPoolSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_pool.TAKE_OFF_PLACE
     *
     * @return the value of plane_pool.TAKE_OFF_PLACE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getTakeOffPlace() {
        return takeOffPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_pool.TAKE_OFF_PLACE
     *
     * @param takeOffPlace the value for plane_pool.TAKE_OFF_PLACE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTakeOffPlace(Integer takeOffPlace) {
        this.takeOffPlace = takeOffPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_pool.TAKE_ON_PLACE
     *
     * @return the value of plane_pool.TAKE_ON_PLACE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getTakeOnPlace() {
        return takeOnPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_pool.TAKE_ON_PLACE
     *
     * @param takeOnPlace the value for plane_pool.TAKE_ON_PLACE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTakeOnPlace(Integer takeOnPlace) {
        this.takeOnPlace = takeOnPlace;
    }

    @Override public String toString() {
        return "PlanePool{" +
                "ticketPoolId=" + ticketPoolId +
                ", planeInfoId=" + planeInfoId +
                ", ticketPoolSum=" + ticketPoolSum +
                ", ticketPoolSale=" + ticketPoolSale +
                ", takeOffPlace=" + takeOffPlace +
                ", takeOnPlace=" + takeOnPlace +
                '}';
    }
}