package com.chen.plane.domain.pojo;

import java.util.Date;

public class PlanePool {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_pool.TICKET_POOL_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer ticketPoolId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_pool.PLANE_INFO_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer planeInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_pool.TICKET_POOL_SUM
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer ticketPoolSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_pool.TICKET_POOL_SALE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer ticketPoolSale;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_pool.TAKE_OFF_PLACE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer planeStartPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_pool.TAKE_ON_PLACE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer planeEndPlace;
    /**
     * 起飞时间
     */
    private Date planeStartTime;
    /**
     * 结束时间
     */
    private Date planeEndTime;
    /**
     * 航班名称
     */
    private String planeName;
    /**
     * 航空公司
     */
    private String planeAirline;

    private Integer cabinId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_pool.TICKET_POOL_ID
     *
     * @return the value of plane_pool.TICKET_POOL_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getTicketPoolId() {
        return ticketPoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_pool.TICKET_POOL_ID
     *
     * @param ticketPoolId the value for plane_pool.TICKET_POOL_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketPoolId(Integer ticketPoolId) {
        this.ticketPoolId = ticketPoolId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_pool.PLANE_INFO_ID
     *
     * @return the value of plane_pool.PLANE_INFO_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getPlaneInfoId() {
        return planeInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_pool.PLANE_INFO_ID
     *
     * @param planeInfoId the value for plane_pool.PLANE_INFO_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPlaneInfoId(Integer planeInfoId) {
        this.planeInfoId = planeInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_pool.TICKET_POOL_SUM
     *
     * @return the value of plane_pool.TICKET_POOL_SUM
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getTicketPoolSum() {
        return ticketPoolSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_pool.TICKET_POOL_SUM
     *
     * @param ticketPoolSum the value for plane_pool.TICKET_POOL_SUM
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketPoolSum(Integer ticketPoolSum) {
        this.ticketPoolSum = ticketPoolSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_pool.TICKET_POOL_SALE
     *
     * @return the value of plane_pool.TICKET_POOL_SALE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getTicketPoolSale() {
        return ticketPoolSale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_pool.TICKET_POOL_SALE
     *
     * @param ticketPoolSale the value for plane_pool.TICKET_POOL_SALE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketPoolSale(Integer ticketPoolSale) {
        this.ticketPoolSale = ticketPoolSale;
    }

    public Integer getPlaneStartPlace() {
        return planeStartPlace;
    }

    public void setPlaneStartPlace(Integer planeStartPlace) {
        this.planeStartPlace = planeStartPlace;
    }

    public Integer getPlaneEndPlace() {
        return planeEndPlace;
    }

    public void setPlaneEndPlace(Integer planeEndPlace) {
        this.planeEndPlace = planeEndPlace;
    }

    public Date getPlaneStartTime() {
        return planeStartTime;
    }

    public void setPlaneStartTime(Date planeStartTime) {
        this.planeStartTime = planeStartTime;
    }

    public Date getPlaneEndTime() {
        return planeEndTime;
    }

    public void setPlaneEndTime(Date planeEndTime) {
        this.planeEndTime = planeEndTime;
    }

    public String getPlaneName() {
        return planeName;
    }

    public void setPlaneName(String planeName) {
        this.planeName = planeName;
    }

    public String getPlaneAirline() {
        return planeAirline;
    }

    public void setPlaneAirline(String planeAirline) {
        this.planeAirline = planeAirline;
    }

    public Integer getCabinId() {
        return cabinId;
    }

    public void setCabinId(Integer cabinId) {
        this.cabinId = cabinId;
    }

    @Override public String toString() {
        return "PlanePool{" +
                "ticketPoolId=" + ticketPoolId +
                ", planeInfoId=" + planeInfoId +
                ", ticketPoolSum=" + ticketPoolSum +
                ", ticketPoolSale=" + ticketPoolSale +
                ", planeStartPlace=" + planeStartPlace +
                ", planeEndPlace=" + planeEndPlace +
                ", planeStartTime=" + planeStartTime +
                ", planeEndTime=" + planeEndTime +
                ", planeName='" + planeName + '\'' +
                ", planeAirline='" + planeAirline + '\'' +
                ", cabinId=" + cabinId +
                '}';
    }
}