package com.chen.plane.domain.pojo;

import java.util.Date;

public class PlaneTicket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_ticket.PLANE_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer planeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_ticket.PLANE_NAME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String planeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_ticket.PLANE_AIRLINE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String planeAirline;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_ticket.PLANE_START_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Date planeStartTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_ticket.PLANE_END_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Date planeEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_ticket.PLANE_START_PLACE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer planeStartPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_ticket.PLANE_END_PLACE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer planeEndPlace;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_ticket.PLANE_INFO_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer planeInfoId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_ticket.PLANE_ID
     *
     * @return the value of plane_ticket.PLANE_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getPlaneId() {
        return planeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_ticket.PLANE_ID
     *
     * @param planeId the value for plane_ticket.PLANE_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPlaneId(Integer planeId) {
        this.planeId = planeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_ticket.PLANE_NAME
     *
     * @return the value of plane_ticket.PLANE_NAME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getPlaneName() {
        return planeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_ticket.PLANE_NAME
     *
     * @param planeName the value for plane_ticket.PLANE_NAME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPlaneName(String planeName) {
        this.planeName = planeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_ticket.PLANE_AIRLINE
     *
     * @return the value of plane_ticket.PLANE_AIRLINE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getPlaneAirline() {
        return planeAirline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_ticket.PLANE_AIRLINE
     *
     * @param planeAirline the value for plane_ticket.PLANE_AIRLINE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPlaneAirline(String planeAirline) {
        this.planeAirline = planeAirline;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_ticket.PLANE_START_TIME
     *
     * @return the value of plane_ticket.PLANE_START_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Date getPlaneStartTime() {
        return planeStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_ticket.PLANE_START_TIME
     *
     * @param planeStartTime the value for plane_ticket.PLANE_START_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPlaneStartTime(Date planeStartTime) {
        this.planeStartTime = planeStartTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_ticket.PLANE_END_TIME
     *
     * @return the value of plane_ticket.PLANE_END_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Date getPlaneEndTime() {
        return planeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_ticket.PLANE_END_TIME
     *
     * @param planeEndTime the value for plane_ticket.PLANE_END_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPlaneEndTime(Date planeEndTime) {
        this.planeEndTime = planeEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_ticket.PLANE_START_PLACE
     *
     * @return the value of plane_ticket.PLANE_START_PLACE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getPlaneStartPlace() {
        return planeStartPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_ticket.PLANE_START_PLACE
     *
     * @param planeStartPlace the value for plane_ticket.PLANE_START_PLACE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPlaneStartPlace(Integer planeStartPlace) {
        this.planeStartPlace = planeStartPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_ticket.PLANE_END_PLACE
     *
     * @return the value of plane_ticket.PLANE_END_PLACE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getPlaneEndPlace() {
        return planeEndPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_ticket.PLANE_END_PLACE
     *
     * @param planeEndPlace the value for plane_ticket.PLANE_END_PLACE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPlaneEndPlace(Integer planeEndPlace) {
        this.planeEndPlace = planeEndPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_ticket.PLANE_INFO_ID
     *
     * @return the value of plane_ticket.PLANE_INFO_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getPlaneInfoId() {
        return planeInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_ticket.PLANE_INFO_ID
     *
     * @param planeInfoId the value for plane_ticket.PLANE_INFO_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPlaneInfoId(Integer planeInfoId) {
        this.planeInfoId = planeInfoId;
    }

    @Override public String toString() {
        return "PlaneTicket{" +
                "planeId=" + planeId +
                ", planeName='" + planeName + '\'' +
                ", planeAirline='" + planeAirline + '\'' +
                ", planeStartTime=" + planeStartTime +
                ", planeEndTime=" + planeEndTime +
                ", planeStartPlace=" + planeStartPlace +
                ", planeEndPlace=" + planeEndPlace +
                ", planeInfoId=" + planeInfoId +
                '}';
    }
}