package com.chen.plane.domain.pojo;

public class PlaneFirst {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_first.CABIN_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer cabinId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_first.CABIN_FIRST_SUM
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer cabinFirstSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_first.CABIN_ONE_SUM
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer cabinOneSum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_first.CABIN_PARTICULAR_SEAT
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String cabinParticularSeat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_first.CABIN_CLOSE_SEAT
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String cabinCloseSeat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_first.CABIN_ALEARDY_SEAT
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String cabinAleardySeat;
    /**
     * 身份证号码
     */
    private String ticketCard;
    /**
     * 总票价
     */
    private Double ticketMoney;
    /**
     * 订票人姓名
     */
    private String ticketName;
    /**
     * 用户ID
     */
    private Integer userId;

    public Integer getUserId() {
        return userId;
    }

    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    @Override public String toString() {
        return "PlaneFirst{" +
                "cabinId=" + cabinId +
                ", cabinFirstSum=" + cabinFirstSum +
                ", cabinOneSum=" + cabinOneSum +
                ", cabinParticularSeat='" + cabinParticularSeat + '\'' +
                ", cabinCloseSeat='" + cabinCloseSeat + '\'' +
                ", cabinAleardySeat='" + cabinAleardySeat + '\'' +
                ", ticketCard='" + ticketCard + '\'' +
                ", ticketMoney=" + ticketMoney +
                ", ticketName='" + ticketName + '\'' +
                ", userId=" + userId +
                '}';
    }

    public String getTicketName() {
        return ticketName;
    }

    public void setTicketName(String ticketName) {
        this.ticketName = ticketName;
    }

    public String getTicketCard() {
        return ticketCard;
    }

    public void setTicketCard(String ticketCard) {
        this.ticketCard = ticketCard;
    }

    public Double getTicketMoney() {
        return ticketMoney;
    }

    public void setTicketMoney(Double ticketMoney) {
        this.ticketMoney = ticketMoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_first.CABIN_ID
     *
     * @return the value of plane_first.CABIN_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getCabinId() {
        return cabinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_first.CABIN_ID
     *
     * @param cabinId the value for plane_first.CABIN_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setCabinId(Integer cabinId) {
        this.cabinId = cabinId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_first.CABIN_FIRST_SUM
     *
     * @return the value of plane_first.CABIN_FIRST_SUM
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getCabinFirstSum() {
        return cabinFirstSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_first.CABIN_FIRST_SUM
     *
     * @param cabinFirstSum the value for plane_first.CABIN_FIRST_SUM
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setCabinFirstSum(Integer cabinFirstSum) {
        this.cabinFirstSum = cabinFirstSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_first.CABIN_ONE_SUM
     *
     * @return the value of plane_first.CABIN_ONE_SUM
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getCabinOneSum() {
        return cabinOneSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_first.CABIN_ONE_SUM
     *
     * @param cabinOneSum the value for plane_first.CABIN_ONE_SUM
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setCabinOneSum(Integer cabinOneSum) {
        this.cabinOneSum = cabinOneSum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_first.CABIN_PARTICULAR_SEAT
     *
     * @return the value of plane_first.CABIN_PARTICULAR_SEAT
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getCabinParticularSeat() {
        return cabinParticularSeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_first.CABIN_PARTICULAR_SEAT
     *
     * @param cabinParticularSeat the value for plane_first.CABIN_PARTICULAR_SEAT
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setCabinParticularSeat(String cabinParticularSeat) {
        this.cabinParticularSeat = cabinParticularSeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_first.CABIN_CLOSE_SEAT
     *
     * @return the value of plane_first.CABIN_CLOSE_SEAT
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getCabinCloseSeat() {
        return cabinCloseSeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_first.CABIN_CLOSE_SEAT
     *
     * @param cabinCloseSeat the value for plane_first.CABIN_CLOSE_SEAT
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setCabinCloseSeat(String cabinCloseSeat) {
        this.cabinCloseSeat = cabinCloseSeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_first.CABIN_ALEARDY_SEAT
     *
     * @return the value of plane_first.CABIN_ALEARDY_SEAT
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getCabinAleardySeat() {
        return cabinAleardySeat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_first.CABIN_ALEARDY_SEAT
     *
     * @param cabinAleardySeat the value for plane_first.CABIN_ALEARDY_SEAT
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setCabinAleardySeat(String cabinAleardySeat) {
        this.cabinAleardySeat = cabinAleardySeat;
    }

}