package com.chen.plane.domain.pojo;

public class PlaneInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_info.PLANE_INFO_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer planeInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_info.PLANE_INTO_SUM_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer planeIntoSumNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_info.PLANE_BUSINESS_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer planeBusinessId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_info.PLANE_ECONOMIC_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer planeEconomicId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column plane_info.PLANE_FIRST_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer planeFirstId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_info.PLANE_INFO_ID
     *
     * @return the value of plane_info.PLANE_INFO_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getPlaneInfoId() {
        return planeInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_info.PLANE_INFO_ID
     *
     * @param planeInfoId the value for plane_info.PLANE_INFO_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPlaneInfoId(Integer planeInfoId) {
        this.planeInfoId = planeInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_info.PLANE_INTO_SUM_NUMBER
     *
     * @return the value of plane_info.PLANE_INTO_SUM_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getPlaneIntoSumNumber() {
        return planeIntoSumNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_info.PLANE_INTO_SUM_NUMBER
     *
     * @param planeIntoSumNumber the value for plane_info.PLANE_INTO_SUM_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPlaneIntoSumNumber(Integer planeIntoSumNumber) {
        this.planeIntoSumNumber = planeIntoSumNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_info.PLANE_BUSINESS_ID
     *
     * @return the value of plane_info.PLANE_BUSINESS_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getPlaneBusinessId() {
        return planeBusinessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_info.PLANE_BUSINESS_ID
     *
     * @param planeBusinessId the value for plane_info.PLANE_BUSINESS_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPlaneBusinessId(Integer planeBusinessId) {
        this.planeBusinessId = planeBusinessId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_info.PLANE_ECONOMIC_ID
     *
     * @return the value of plane_info.PLANE_ECONOMIC_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getPlaneEconomicId() {
        return planeEconomicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_info.PLANE_ECONOMIC_ID
     *
     * @param planeEconomicId the value for plane_info.PLANE_ECONOMIC_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPlaneEconomicId(Integer planeEconomicId) {
        this.planeEconomicId = planeEconomicId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column plane_info.PLANE_FIRST_ID
     *
     * @return the value of plane_info.PLANE_FIRST_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getPlaneFirstId() {
        return planeFirstId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column plane_info.PLANE_FIRST_ID
     *
     * @param planeFirstId the value for plane_info.PLANE_FIRST_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPlaneFirstId(Integer planeFirstId) {
        this.planeFirstId = planeFirstId;
    }

    @Override public String toString() {
        return "PlaneInfo{" +
                "planeInfoId=" + planeInfoId +
                ", planeIntoSumNumber=" + planeIntoSumNumber +
                ", planeBusinessId=" + planeBusinessId +
                ", planeEconomicId=" + planeEconomicId +
                ", planeFirstId=" + planeFirstId +
                '}';
    }
}