package com.chen.plane.domain.pojo;

import java.util.Date;

public class TicketReturn {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_return.TICKET_RETURN_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer ticketReturnId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_return.TICKET_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer ticketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_return.TICKET_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Date ticketTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_return.TICKET_RETURN_IP
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String ticketReturnIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_return.TICKET_RETURN_STATUE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer ticketReturnStatue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_return.TICKET_RETURN_MONEY_STATUE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer ticketReturnMoneyStatue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket_return.TICKET_RETURN_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String ticketReturnNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_return.TICKET_RETURN_ID
     *
     * @return the value of ticket_return.TICKET_RETURN_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getTicketReturnId() {
        return ticketReturnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_return.TICKET_RETURN_ID
     *
     * @param ticketReturnId the value for ticket_return.TICKET_RETURN_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketReturnId(Integer ticketReturnId) {
        this.ticketReturnId = ticketReturnId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_return.TICKET_ID
     *
     * @return the value of ticket_return.TICKET_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_return.TICKET_ID
     *
     * @param ticketId the value for ticket_return.TICKET_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_return.TICKET_TIME
     *
     * @return the value of ticket_return.TICKET_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Date getTicketTime() {
        return ticketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_return.TICKET_TIME
     *
     * @param ticketTime the value for ticket_return.TICKET_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketTime(Date ticketTime) {
        this.ticketTime = ticketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_return.TICKET_RETURN_IP
     *
     * @return the value of ticket_return.TICKET_RETURN_IP
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getTicketReturnIp() {
        return ticketReturnIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_return.TICKET_RETURN_IP
     *
     * @param ticketReturnIp the value for ticket_return.TICKET_RETURN_IP
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketReturnIp(String ticketReturnIp) {
        this.ticketReturnIp = ticketReturnIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_return.TICKET_RETURN_STATUE
     *
     * @return the value of ticket_return.TICKET_RETURN_STATUE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getTicketReturnStatue() {
        return ticketReturnStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_return.TICKET_RETURN_STATUE
     *
     * @param ticketReturnStatue the value for ticket_return.TICKET_RETURN_STATUE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketReturnStatue(Integer ticketReturnStatue) {
        this.ticketReturnStatue = ticketReturnStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_return.TICKET_RETURN_MONEY_STATUE
     *
     * @return the value of ticket_return.TICKET_RETURN_MONEY_STATUE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getTicketReturnMoneyStatue() {
        return ticketReturnMoneyStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_return.TICKET_RETURN_MONEY_STATUE
     *
     * @param ticketReturnMoneyStatue the value for ticket_return.TICKET_RETURN_MONEY_STATUE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketReturnMoneyStatue(Integer ticketReturnMoneyStatue) {
        this.ticketReturnMoneyStatue = ticketReturnMoneyStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket_return.TICKET_RETURN_NUMBER
     *
     * @return the value of ticket_return.TICKET_RETURN_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getTicketReturnNumber() {
        return ticketReturnNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket_return.TICKET_RETURN_NUMBER
     *
     * @param ticketReturnNumber the value for ticket_return.TICKET_RETURN_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketReturnNumber(String ticketReturnNumber) {
        this.ticketReturnNumber = ticketReturnNumber;
    }

    @Override public String toString() {
        return "TicketReturn{" +
                "ticketReturnId=" + ticketReturnId +
                ", ticketId=" + ticketId +
                ", ticketTime=" + ticketTime +
                ", ticketReturnIp='" + ticketReturnIp + '\'' +
                ", ticketReturnStatue=" + ticketReturnStatue +
                ", ticketReturnMoneyStatue=" + ticketReturnMoneyStatue +
                ", ticketReturnNumber='" + ticketReturnNumber + '\'' +
                '}';
    }
}