package com.chen.plane.domain.pojo;

import java.util.Date;

public class Ticket {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.TICKET_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer ticketId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.TICKET_NAME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String ticketName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.TICKET_CARD
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String ticketCard;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.TICKET_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Date ticketTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.PAY_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer payId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.TICKET_STATUE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer ticketStatue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.USER_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.TICKET_IP
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String ticketIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ticket.TICKET_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String ticketNumber;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.TICKET_ID
     *
     * @return the value of ticket.TICKET_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getTicketId() {
        return ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.TICKET_ID
     *
     * @param ticketId the value for ticket.TICKET_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketId(Integer ticketId) {
        this.ticketId = ticketId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.TICKET_NAME
     *
     * @return the value of ticket.TICKET_NAME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getTicketName() {
        return ticketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.TICKET_NAME
     *
     * @param ticketName the value for ticket.TICKET_NAME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketName(String ticketName) {
        this.ticketName = ticketName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.TICKET_CARD
     *
     * @return the value of ticket.TICKET_CARD
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getTicketCard() {
        return ticketCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.TICKET_CARD
     *
     * @param ticketCard the value for ticket.TICKET_CARD
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketCard(String ticketCard) {
        this.ticketCard = ticketCard;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.TICKET_TIME
     *
     * @return the value of ticket.TICKET_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Date getTicketTime() {
        return ticketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.TICKET_TIME
     *
     * @param ticketTime the value for ticket.TICKET_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketTime(Date ticketTime) {
        this.ticketTime = ticketTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.PAY_ID
     *
     * @return the value of ticket.PAY_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getPayId() {
        return payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.PAY_ID
     *
     * @param payId the value for ticket.PAY_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setPayId(Integer payId) {
        this.payId = payId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.TICKET_STATUE
     *
     * @return the value of ticket.TICKET_STATUE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getTicketStatue() {
        return ticketStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.TICKET_STATUE
     *
     * @param ticketStatue the value for ticket.TICKET_STATUE
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketStatue(Integer ticketStatue) {
        this.ticketStatue = ticketStatue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.USER_ID
     *
     * @return the value of ticket.USER_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.USER_ID
     *
     * @param userId the value for ticket.USER_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.TICKET_IP
     *
     * @return the value of ticket.TICKET_IP
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getTicketIp() {
        return ticketIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.TICKET_IP
     *
     * @param ticketIp the value for ticket.TICKET_IP
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketIp(String ticketIp) {
        this.ticketIp = ticketIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ticket.TICKET_NUMBER
     *
     * @return the value of ticket.TICKET_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getTicketNumber() {
        return ticketNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ticket.TICKET_NUMBER
     *
     * @param ticketNumber the value for ticket.TICKET_NUMBER
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setTicketNumber(String ticketNumber) {
        this.ticketNumber = ticketNumber;
    }

    @Override public String toString() {
        return "Ticket{" +
                "ticketId=" + ticketId +
                ", ticketName='" + ticketName + '\'' +
                ", ticketCard='" + ticketCard + '\'' +
                ", ticketTime=" + ticketTime +
                ", payId=" + payId +
                ", ticketStatue=" + ticketStatue +
                ", userId=" + userId +
                ", ticketIp='" + ticketIp + '\'' +
                ", ticketNumber='" + ticketNumber + '\'' +
                '}';
    }
}