package com.chen.plane.domain.pojo;

import java.io.Serializable;
import java.util.Date;

public class User implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_NAME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_PWD
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String userPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_IP
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private String userIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.USER_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    private Date userTime;
    /**
     * 用户登录口令
     */
    private String accessToken;
    /**
     * 访问Token过期时间
     */
    private Date accessTokenExpiryTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_ID
     *
     * @return the value of user.USER_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_ID
     *
     * @param userId the value for user.USER_ID
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_NAME
     *
     * @return the value of user.USER_NAME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_NAME
     *
     * @param userName the value for user.USER_NAME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setUserName(String userName) {
        this.userName = userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_PWD
     *
     * @return the value of user.USER_PWD
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getUserPwd() {
        return userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_PWD
     *
     * @param userPwd the value for user.USER_PWD
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setUserPwd(String userPwd) {
        this.userPwd = userPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_IP
     *
     * @return the value of user.USER_IP
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public String getUserIp() {
        return userIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_IP
     *
     * @param userIp the value for user.USER_IP
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setUserIp(String userIp) {
        this.userIp = userIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.USER_TIME
     *
     * @return the value of user.USER_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public Date getUserTime() {
        return userTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.USER_TIME
     *
     * @param userTime the value for user.USER_TIME
     *
     * @mbggenerated Thu Jan 28 15:38:52 CST 2016
     */
    public void setUserTime(Date userTime) {
        this.userTime = userTime;
    }

    public String getAccessToken() {
        return accessToken;
    }

    public void setAccessToken(String accessToken) {
        this.accessToken = accessToken;
    }

    public Date getAccessTokenExpiryTime() {
        return accessTokenExpiryTime;
    }

    public void setAccessTokenExpiryTime(Date accessTokenExpiryTime) {
        this.accessTokenExpiryTime = accessTokenExpiryTime;
    }

    @Override public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;

        User user = (User) o;

        if (!userId.equals(user.userId))
            return false;
        if (!userName.equals(user.userName))
            return false;
        if (!userPwd.equals(user.userPwd))
            return false;
        if (!userIp.equals(user.userIp))
            return false;
        if (userTime != null ? !userTime.equals(user.userTime) : user.userTime != null)
            return false;
        if (accessToken != null ? !accessToken.equals(user.accessToken) : user.accessToken != null)
            return false;
        return !(accessTokenExpiryTime != null ? !accessTokenExpiryTime.equals(user.accessTokenExpiryTime) : user.accessTokenExpiryTime != null);

    }

    @Override public int hashCode() {
        int result = userId.hashCode();
        result = 31 * result + userName.hashCode();
        result = 31 * result + userPwd.hashCode();
        result = 31 * result + userIp.hashCode();
        result = 31 * result + (userTime != null ? userTime.hashCode() : 0);
        result = 31 * result + (accessToken != null ? accessToken.hashCode() : 0);
        result = 31 * result + (accessTokenExpiryTime != null ? accessTokenExpiryTime.hashCode() : 0);
        return result;
    }

    @Override public String toString() {
        return "User{" +
                "userId=" + userId +
                ", userName='" + userName + '\'' +
                ", userPwd='" + userPwd + '\'' +
                ", userIp='" + userIp + '\'' +
                ", userTime=" + userTime +
                ", accessToken='" + accessToken + '\'' +
                ", accessTokenExpiryTime=" + accessTokenExpiryTime +
                '}';
    }
}